package com.proyecto_integrador_3.Estetica.Enums;

public enum Tratamiento {

	FACIALES_ANTIAGE,
	FACIALES_DESPIGMENTANTES,
	FACIALES_HIDRATANTES,
	FACIALES_ROSACEAS,
	FACIALES_ANTIACNE,
	LIFTING_PESTAÑAS,
	PERFILADO_CEJAS,
	LAMINADO_CEJAS,
	HYDRALIPS, 
	LIMPIEZA_ESPALDA;
}
